# Generated by Django 5.2.6 on 2025-11-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='deposit',
        ),
    ]
