# Generated by Django 5.2.6 on 2025-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['start_date', 'start_time'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='manually_fully_booked',
            field=models.BooleanField(default=False, help_text='Check this to manually mark the class as fully booked (e.g., for bookings received via phone/email)'),
        ),
        migrations.AddField(
            model_name='class',
            name='max_capacity',
            field=models.IntegerField(default=10, help_text='Maximum number of attendees'),
        ),
    ]
