# Generated by Django 4.2.26 on 2025-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This name will be displayed publicly with your testimonial', max_length=100),
        ),
    ]
